### ISSUE TITLE
pinkFalcon please add facial recognition module

### ISSUE THREAD

**Issue by Shrivis** [Shrivis/NewProject#2]

**Comment by Shrivis** [comment]
Uploaded all the required files. Merge it so I could make further changes

**Comment by Shrivis** [comment]
I'll dm the details of the changes we talked about

**Comment by PinkFalcon** [comment]
uploaded all the required files. merge the pr

**Comment by PinkFalcon** [comment]
I'll dm the details related to change in root modules att. we will further implement the changes according to all four of us
